version: '3.8'
services:
  web:
    build: .
    command: python webapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Par défaut, utilisation de SQLite
      DATABASE_ENGINE: "django.db.backends.sqlite3"
      DATABASE_NAME: "db.sqlite3"
      # Pour une configuration PostgreSQL, modifiez les variables suivantes et décommentez le service db
      # DATABASE_ENGINE: "django.db.backends.postgresql"
      # DATABASE_NAME: "worldpress_db"
      # DATABASE_USER: "worldpress_user"
      # DATABASE_PASSWORD: "worldpress_password"
      # DATABASE_HOST: "db"
      # DATABASE_PORT: "5432"

  # Optionnel : service db pour PostgreSQL
  # Pour utiliser PostgreSQL, décommentez cette section et mettez à jour vos variables dans le service web.
  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_DB: worldpress_db
  #     POSTGRES_USER: worldpress_user
  #     POSTGRES_PASSWORD: worldpress_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

# Optionnel : définition d'un volume pour la persistance de PostgreSQL
# volumes:
#   postgres_data:
