[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "gallery.settings"
pythonpath = [".", "webapp"]
testpaths = ["APIPictures/tests", "webapp/authentication/tests/", "webapp/pictures/tests/"]
python_files = ["test_*.py"]
addopts = [
    "-ra",
    "--strict-markers",
    "--disable-warnings",
    "--cov=APIPictures",
    "--cov=webapp",
    "--cov=webapp/authentication",
    "--cov=webapp/pictures",
    "--cov-report=term-missing",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.coverage.run]
branch = true
omit = [
    "*/tests/*",
    "*/__init__.py",
    "*/settings.py",
    "*middlewares.py",
    "*/migrations/*",
    "*/wsgi.py",
    "*/asgi.py",
    "manage.py", 
]

[tool.coverage.report]
show_missing = true
fail_under = 80


[flake8]
max-line-length = 88
exclude = 
    .venv,
    venv,
    migrations,
    __pycache__,
    manage.py
ignore =
    E203  
    W503  
    F401  
    F403  
    F405  
    E501  
    B905  
statistics = True
count = True

