# Generated by Django 4.2.3 on 2023-08-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer_text',
            field=models.TextField(default=False, verbose_name='Caption'),
        ),
    ]
