# Generated by Django 4.2.3 on 2023-08-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('time_limit_minutes', models.PositiveBigIntegerField(default=10, verbose_name='Time Limit (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image Url')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='photoquiz.quiz')),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100, verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='photoquiz.event')),
            ],
            options={
                'verbose_name': 'Answer',
            },
        ),
    ]
