# Generated by Django 4.2.3 on 2023-08-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoquiz', '0002_answer_correct_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
