# Generated by Django 4.2.3 on 2023-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=100)),
                ('sectionTitle', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField()),
                ('pageUrl', models.URLField()),
                ('caption', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('credits', models.CharField(blank=True, max_length=50)),
                ('picture', models.URLField()),
                ('rating', models.IntegerField(default=0, null=True)),
                ('pictureEditor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('caption', 'picture')},
            },
        ),
    ]
