# Generated by Django 4.2.3 on 2023-08-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['-pubDate'], 'verbose_name': 'Picture'},
        ),
    ]
