# Generated by Django 4.2.3 on 2023-08-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_alter_photogallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='rating',
        ),
    ]
